/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ie_agisoft_Test */

#ifndef _Included_ie_agisoft_Test
#define _Included_ie_agisoft_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ie_agisoft_Test
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ie_agisoft_Test_hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
